services:
  - type: web
    name: predictiveguard
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=/app/PredictiveGuard.db"
      - key: ApiBaseUrl
        value: "http://127.0.0.1:5000"
